Rewrite `enarx-pr-request` as consumable with GraphQL
enarx/bot pull request #66
Opened 2020-08-27 21:06 UTC by mbestavros

This is a pretty significant rewrite. Though the logic for selecting reviewers is much the same as in the original, the API interaction has changed significantly.

Thanks to the information available to us from the `pull_request_target` event this action runs on, I was able to pull down _everything_ needed for this action in a single GraphQL call.

2020-08-31 12:22 UTC, ueno submitted a review, later dismissed
This looks tidy :+1:

2020-09-22 18:36 UTC, npmccallum requested changes
As discussed on the phone, @mbestavros will decrease the density of some of the code blocks to make things a bit more readable. Please also run a python linter on this code.

2020-09-28 15:22 UTC, npmccallum requested changes
1. Investigate query fragments to reduce query size.
2. Create an `iterusers()` function to flatten user data from query data.
3. Create multiple lookup tables (`login_to_id`, `availability`, etc).

2020-10-05 16:59 UTC, mbestavros commented
@npmccallum This should be ready for a re-review. All three items above are done.

2020-10-09 18:41 UTC, npmccallum requested changes
Have `iterusers()` use `yield` and `yield from`.

2020-10-09 20:58 UTC, npmccallum approved these changes

2020-10-12 13:40 UTC, ueno approved these changes

2020-10-12 14:01 UTC, merged