Rewrite sprint board cleanup in GraphQL
enarx/bot pull request #79
Opened 2020-10-07 21:26 UTC by mbestavros

This will allow us to remove all traces of PyGithub and API v3 from the Enarxbot.

Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

2020-10-09 18:59 UTC, npmccallum commented on enarxbot-post-sprint-cleanup
> +    """,
Split out this query.

2020-10-09 19:03 UTC, npmccallum requested changes
Move out the mutations into variables.

2020-10-09 20:59 UTC, npmccallum approved these changes

2020-10-13 14:36 UTC, ueno approved these changes

2020-10-13 15:01 UTC, merged