Tidy up log output to make active actions more explicit
enarx/bot pull request #87
Opened 2020-10-19 21:55 UTC by mbestavros

Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

2020-10-20 13:18 UTC, lkatalin approved these changes

2020-10-20 13:37 UTC, npmccallum requested changes

2020-10-20 13:37 UTC, npmccallum commented on action.yml
> +      shell: bash
Can we print the log header here instead of polluting the scripts? If not, okay.

2020-10-20 20:01 UTC, mbestavros commented
@npmccallum Done. Note that I've also moved the environment variable and event JSON dump to after the script execution -- the script logs will almost always be more interesting to us, and will be better to see first (without having to scroll past the env variables).

2020-10-22 17:47 UTC, npmccallum approved these changes

2020-10-22 17:49 UTC, lkatalin approved these changes

2020-10-22 18:04 UTC, merged